name: 'Action for read app version'
description: 'Reading app version from file'
author: 'APS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

inputs:
  ver_file: # id of input
    description: 'File for handling'
    required: true
    default: 'none'
  defined_version_var:
    description: 'defined var for version tag'
    required: true
    default: 'FIRMWARE_VERSION'
outputs:
  result_version: # id of output
    description: 'Result current app version'

runs:
  using: node20
  main: dist/index.js
