# action.yml
name: 'Read version'
description: 'Getting app version from file'
inputs:
  exec_file:
    description: 'File for execution'
    required: true
    default: 'get_c_version.py'
  ver_file:  # id of input
    description: 'File for handling'
    required: true
    default: ''
  defined_version_var:  
    description: 'defined var for version tag'
    required: true
    default: 'FIRMWARE_VERSION'
outputs:
  result_version: # id of output
    description: 'Result current app version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f
    - ${{ inputs.ver_file }}
    - -d
    - ${{ inputs.defined_version_var }}
